### ISSUE TITLE
[Awesome Green Software] Content curators to add to the Awesome Green Software project

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/community-wg#24]
The awesome green software project is a one-page resource of every resource that might be useful to someone exploring applying green software practices. From tooling to research.

If you have some content that you think would benefit the list to be added then either directly create a pull request to add the content to the list by clicking the red edit pencil or whatever method you are comfortable doing so.

You can also join the [#proj-awesome-green-software ](https://greensoftwarefdn.slack.com/archives/C02LHAW0KKQ)channel on slack.

**Comment by holanita** [comment]
Hi all – is this issue still to be tackled within the Community WG? If it is, what would be the next step(s)?
