### ISSUE TITLE
[Software Carbon Intensity Specification] Do you want to calculate a green score for your application?

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/community-wg#25]
The Software Carbon Intensity Specification is a methodology for calculating a score for how sustainable your software application is. Lower numbers are better than higher numbers and reaching zero is impossible. 

The project has reached an alpha milestone and is now working on applying the specification to real-world case studies.

The team is looking for people who are interested in helping calculate an SCI score for their (or other people's) applications. If you are interested in taking part then please reach out to the chairs of the Standards Working Group or message in the [#wg-standards](https://greensoftwarefdn.slack.com/archives/C027QDQSA8M) Slack channel.

**Comment by atg-abhishek** [comment]
You can read the spec [here](https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/main/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md)

**Comment by holanita** [comment]
Hi all – is this issue still to be tackled within the Community WG? If it is, what would be the next step(s)?
