### ISSUE TITLE
[Action Item] Earth Day - Saturday, 22 April

### ISSUE THREAD

**Issue by tmcclell** [Green-Software-Foundation/community-wg#26]
Would like to propose that we assign a subgroup to come up with promotional ideas for Earth Day - April, 2022.

**Comment by seanmcilroy29** [comment]
Proposal - https://cyberworldcleanupday.fr/welcome/

**Comment by seanmcilroy29** [comment]
# Earth Day - Saturday, 22 April

- [ ] Meetup
- [ ] Showcase the winners of the Hack22
- [ ] Showcase SCI usecases
- [ ] Promote the trg together - Study session - LF Cert day -
- [ ] Which day to target

**Comment by holanita** [comment]
- Shall we promote **the SOGS report** as well as it is scheduled to come out at the end of Q3?
- Also, earlier we talked about **adding new features to the Speakers Bureau** for Earth Day. See the Pr FAQ and below:
_The Speakers Bureau is also intended as support for GSF members in their speaking engagements. Not only is it capable of promoting speakers, but the platform will be able to cross the bridge to speaker resources and materials, speaker training, mentoring and education, to truly foster a best-in-class environment. These features are planned for the version 2.0 release in April 2023 ahead of Earth Day._
