### ISSUE TITLE
[GSF Writers] Translating articles and other GSF content to other languages

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/community-wg#3]
One of our core pillars is inclusion and to achieve that we need to be accessible to the world which means having our content in multiple languages.

If you are interested in helping translate [one of our articles](https://greensoftware.foundation/articles) or other pages on the website then please message the team in the [#proj-writers](https://greensoftwarefdn.slack.com/archives/C02FCC3BDUZ) slack room or email helpdesk@greensoftware.foundation

For more info please take look at the [translation spreadsheet](https://docs.google.com/spreadsheets/d/17e70VPNGmt38wv9thVWfYOvTgeYfhGLL7z7N5_92aM0/edit?usp=sharing) and take a look the [GSF Writers project page](https://greensoftware.foundation/projects/writers) on our website.

**Comment by SaraEmilyBergman** [comment]
Update: We now have a separate Slack channel dedicated to translations! You can message the team in [#proj-writers-translations](https://greensoftwarefdn.slack.com/archives/C02KZL4PVRU).

**Comment by alanverdugo** [comment]
Hi there! I am interested in helping with translations! :)
I am a native Spanish speaker.
I tried to join the Slack channel but it is asking me to login with a @microsoft.com account or any other member domain address.
I promise I've been trying to join Microsoft for some time, but meanwhile, can I still help you with the translations?
I apologize in advance if I am doing this wrong!

**Comment by elliatab** [comment]
Hi @SaraEmilyBergman, I am interested in helping with translations to French. 
I also sent an email to [helpdesk@greensoftware.foundation](mailto:helpdesk@greensoftware.foundation)

**Comment by SaraEmilyBergman** [comment]
Hello @alanverdugo so excited to have you! Could you please reach out to helpdesk to get some assistance on joining slack? You will likely need to create a shadow google account for your Microsoft email address, but they can assist you better :)

Hello @elliatab this is great, looking forward to having you contribute :) Once you have access to slack as a GSF member it should be smooth sailing to join the slack group and access the documents.

**Comment by wojtekidd** [comment]
Email sent 📧😎
