### ISSUE TITLE
[GSF Writers] Interested in writing an article for the Green Software Foundation?

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/community-wg#4]
Do you want to write content for the GSF webpage? Awesome, you have come to the right place! 

If you have an idea for some original content we have editors and illustrators on staff to support you the whole way through to publication. Alternatively, if you have an article that you have written somewhere else and would like to repost in the GSF, we would also love to talk to you about that also.

Here is the checklist for you:

1. Join the [#proj-writers](https://greensoftwarefdn.slack.com/archives/C02FCC3BDUZ) room in Slack.

2. Make sure your proposed topic is aligned with our themes.

 The [GSF Writers Guidelines](https://docs.google.com/document/u/0/d/11Zk5-6VSylI1-jxPEWse7m-dyAthitUYx0gw9GGPibU/edit) outline the themes we include, make sure your idea is aligned with at least one of these. If you are unsure (or have any other questions) ask in the #proj-writers channel on Slack. If your idea does not match any of the themes, we will not publish it.

3. Read the Writer's guide

The Writer’s guidelines can be found [here](https://docs.google.com/document/u/0/d/11Zk5-6VSylI1-jxPEWse7m-dyAthitUYx0gw9GGPibU/edit) and you should read it before you submit an idea. It is up to you to make sure your article follows the guidelines, if it does not, we might ask you to change it or decide not to publish it. 

4. Ask for a publication date

Once you have a proposal for an article, ask for a publication date in our editorial calendar by asking in the [#proj-writers](https://greensoftwarefdn.slack.com/archives/C02FCC3BDUZ) channel on Slack. You will need to outline your idea of the article but you don’t need to provide a full draft.

5. Send draft for publication

At least three weeks before your publication date, send the draft to Nilooka at Nilooka@greensoftware.foundation for editorial review. Clearly mark if you need any graphics and if you use any other images you must make sure we have the right to publish them. Make sure to use proper titles (e.g. don’t make text bold to indicate titles and subtitles) to make the title hierarchy clear (heading 1, heading 2 etc).

Please note that any original content written for the GSF is Creative Commons attribution, specifically this license: [Creative Commons — Attribution 4.0 International — CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

**Comment by kunalmcitm** [comment]
Do count me in
